cloud:
  project: some-project
  region: europe-west1
  zone: europe-west1-d
  bucket: gs://bucket-name/
model:
  name: model
  num-epochs: 20
  train-batch-size: 100
  eval-batch-size: 100
  test-batch-size: 100
  embedding-size: 8
  first-layer-size: 100
  num-layers: 10
  scale-factor: .7
  train-steps: 1000
  eval-steps: 500
  export-format: JSON
  input-format: csv # [csv, tfrecords]
  verbosity: DEBUG
  label: y # Label column in data set.
  key: false # The identifier in the data set.
path:
  base: ./data/
  external: external/
  intermediate: intermediate/
  processed: processed/
  metadata: processed/metadata/
  raw: raw/
  models: models/
  job: job/
  field-delim: ","
  train-files:
    - processed/train.csv
  test-files:
    - processed/test.csv
  eval-files:
    - processed/eval.csv
  staging: staging/
